#ifndef __APP_ANCHOR_AUTOCALIBRATE_H__
#define __APP_ANCHOR_AUTOCALIBRATE_H__

#define ANCHOR_CALIBRATION_TARGET_DISTANCE 0.3 // meters
#define ANCHOR_CALIBRATION_TRIALS 1
#define ANCHOR_CALIBRATION_INIT_STEP_SIZE 100
#define ANCHOR_CALIBRATION_STARTING_DELAY 16600
#define ANCHOR_CALIBRATION_ADELAY_DELTA 3

extern void app_anchor_autocalibrate(void);

#endif // __APP_ANCHOR_AUTOCALIBRATE_H__